repos:
  - repo: local
    hooks:
      - id: ensure-blank-lines
        name: ensure blank lines around if/else/try/catch
        entry: python3 scripts/ensure-blank-lines.py
        language: system
        types_or: [c, c++]
        exclude: '^(libs/|extern/)'

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        types_or: [c, c++]
        exclude: '^(libs/|extern/)'

